/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and sign in. */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List your files, newest first. */
        get: operations["list"];
        put?: never;
        /**
         * Upload a file.
         * @description The body is streamed to storage, never held in memory. The type is detected from
         *     the bytes and must be on the allow-list; it must also agree with the filename's
         *     extension. Re-uploading bytes you already have returns the existing file with
         *     `200` instead of `201`. New files start as `pending` with an extraction job queued.
         */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete several files at once. */
        post: operations["bulk_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of your files, with the state of its extraction job. */
        get: operations["get"];
        put?: never;
        post?: never;
        /** Delete a file. Its contents are removed once no other file uses them. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Rename, pin/unpin or retag a file. */
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a file's contents (always as an attachment, never rendered inline). */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/extraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The text extracted from one of your files, a window at a time. */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract a file again (e.g. after a failure). Puts it back to `pending`. */
        post: operations["reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Files similar to one of yours, by embedding (mean of the file's chunk vectors). */
        get: operations["similar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A preview of an image file, at most 256 px on its longer side (JPEG, or PNG
         *     for images with transparency).
         * @description Generated in the background after upload: `404` until it exists, and always
         *     `404` for files that have no preview (PDFs, text, media, images too large or
         *     damaged to decode; clients show a type icon instead). Send the `ETag` back in
         *     `If-None-Match` to get `304 Not Modified`.
         */
        get: operations["thumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user. */
        get: operations["get_me"];
        put?: never;
        post?: never;
        /** Permanently delete the account and everything it owns. */
        delete: operations["delete_me"];
        options?: never;
        head?: never;
        /** Update profile fields. */
        patch: operations["update_me"];
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password. Signs out every other session. */
        post: operations["change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search your files; results are grouped by file with their best passages.
         * @description When semantic search is unavailable (model not installed or still loading),
         *     the search runs as keyword search and the response says so (`degraded`,
         *     `warnings`) instead of failing.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search your files passage by passage (chunk-level results with full text,
         *     for agents and citations).
         */
        get: operations["search_chunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process is up. Never touches dependencies. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: the process can serve traffic (database reachable). */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BulkDeleteRequest: {
            /** @description Up to 100 file ids. Ids that are unknown (or not yours) are ignored. */
            ids: string[];
        };
        BulkDeleteResponse: {
            /** @description The ids that were deleted. */
            deleted: string[];
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        /** @description A chunk-level result: the chunk, its full text and its file. */
        ChunkHit: components["schemas"]["ChunkMatch"] & {
            file: components["schemas"]["FileInfo"];
            /** @description The whole chunk text. */
            text: string;
        };
        /** @description A matching chunk, located for citation. */
        ChunkMatch: {
            /** Format: int32 */
            char_end: number;
            /**
             * Format: int32
             * @description `[char_start, char_end)` of the chunk in the file's extracted text (characters).
             */
            char_start: number;
            /** Format: int64 */
            chunk_id: number;
            /** Format: int32 */
            chunk_index: number;
            /**
             * Format: int32
             * @description 1-based PDF page; `null` for formats without pages.
             */
            page?: number | null;
            scores: components["schemas"]["Scores"];
            snippet: components["schemas"]["Snippet"];
        };
        ChunkResults: components["schemas"]["SearchMeta"] & {
            /** @description Best first. */
            results: components["schemas"]["ChunkHit"][];
        };
        DeleteAccountRequest: {
            /** @description Current password, to confirm. */
            password: string;
        };
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /** @description Stable machine-readable code, e.g. `not_found`. */
            code: string;
            message: string;
        };
        ExtractionResponse: {
            /**
             * Format: int32
             * @description Length of the whole text in characters.
             */
            char_count: number;
            /**
             * Format: int64
             * @description Chunks indexed for search.
             */
            chunk_count: number;
            /** Format: date-time */
            created_at: string;
            /**
             * @description `text`, `markdown`, `csv`, `json`, `pdf`, `ocr`, or `none` when nothing could be
             *     extracted (e.g. audio and video, which are not transcribed yet).
             */
            extractor: string;
            extractor_version: string;
            /** Format: uuid */
            file_id: string;
            /**
             * Format: int32
             * @description Pass as `offset` to read on; `null` at the end.
             */
            next_offset?: number | null;
            /** @description Remarks such as "OCR is disabled" or "truncated". */
            notes: string[];
            /**
             * Format: int32
             * @description Character offset of `text` in the whole text.
             */
            offset: number;
            /**
             * Format: int32
             * @description Pages in the document; `null` for formats without pages.
             */
            page_count?: number | null;
            /** @description Page spans, in order (PDFs only). */
            pages: components["schemas"]["PageSpan"][];
            /** @description The requested window of the text. */
            text: string;
        };
        /**
         * @description Broad file kind, for filtering.
         * @enum {string}
         */
        FileCategory: "pdf" | "image" | "audio" | "video" | "text";
        /** @description One file plus the state of its latest processing job. */
        FileDetail: components["schemas"]["FileResponse"] & {
            processing?: null | components["schemas"]["ProcessingJob"];
        };
        /** @description A file-level result: the file and its best matching chunks. */
        FileHit: {
            file: components["schemas"]["FileInfo"];
            /**
             * Format: int32
             * @description Matching chunks of this file among the candidates.
             */
            match_count: number;
            /** @description Up to three best chunks, best first. */
            matches: components["schemas"]["ChunkMatch"][];
            /**
             * Format: double
             * @description The best chunk's fused score.
             */
            score: number;
        };
        /** @description The file a result belongs to. */
        FileInfo: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            is_pinned: boolean;
            mime_type: string;
            name: string;
            /** Format: int64 */
            size_bytes: number;
            /** @description `pending`, `processing`, `ready` or `failed`. */
            status: string;
            tags: string[];
        };
        FileList: {
            /** @description Newest first. */
            items: components["schemas"]["FileResponse"][];
            /** @description Pass as `cursor` to get the next page; `null` on the last page. */
            next_cursor?: string | null;
        };
        FileResponse: {
            /** @description SHA-256 of the contents, lowercase hex. */
            content_hash: string;
            /** Format: date-time */
            created_at: string;
            /** @description Why processing failed, when `status` is `failed`. */
            error?: string | null;
            /** Format: uuid */
            id: string;
            is_pinned: boolean;
            /** @description Detected from the contents, not taken from the client. */
            mime_type: string;
            /** @description Sanitised original filename. */
            name: string;
            /** Format: int64 */
            size_bytes: number;
            status: components["schemas"]["FileStatus"];
            tags: string[];
            /** Format: date-time */
            updated_at: string;
        };
        FileResults: components["schemas"]["SearchMeta"] & {
            /** @description Best first. */
            results: components["schemas"]["FileHit"][];
        };
        /**
         * @description Processing state of a file.
         * @enum {string}
         */
        FileStatus: "pending" | "processing" | "ready" | "failed";
        Health: {
            status: string;
            version: string;
        };
        /** @description A highlighted span of a snippet, `[start, end)` in Unicode characters. */
        Highlight: {
            /** Format: int32 */
            end: number;
            /** Format: int32 */
            start: number;
        };
        /**
         * @description State of a background job.
         * @enum {string}
         */
        JobState: "queued" | "running" | "succeeded" | "failed" | "dead";
        LoginRequest: {
            email: string;
            password: string;
        };
        /**
         * @description Where a PDF page's text came from.
         * @enum {string}
         */
        PageSource: "text" | "ocr" | "needs_ocr" | "unreadable";
        /** @description A PDF page's span in the full text (`char_start..char_end`, in characters). */
        PageSpan: {
            /** Format: int64 */
            char_end: number;
            /** Format: int64 */
            char_start: number;
            /**
             * Format: int32
             * @description 1-based page number.
             */
            number: number;
            source: components["schemas"]["PageSource"];
        };
        ProcessingJob: {
            /**
             * Format: int32
             * @description Attempts started so far.
             */
            attempts: number;
            /** Format: int32 */
            max_attempts: number;
            /**
             * Format: date-time
             * @description When it will next be tried (`queued` or `failed` only).
             */
            next_attempt_at?: string | null;
            stage: components["schemas"]["ProcessingStage"];
            state: components["schemas"]["JobState"];
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Which processing step a job performs.
         * @enum {string}
         */
        ProcessingStage: "extract" | "embed";
        RegisterRequest: {
            display_name?: string | null;
            email: string;
            password: string;
        };
        /** @description Why a chunk ranked where it did. */
        Scores: {
            /**
             * Format: int32
             * @description 1-based rank in the file-name list.
             */
            filename_rank?: number | null;
            /**
             * Format: double
             * @description Reciprocal Rank Fusion score (sum of `1 / (60 + rank)` over the retrievers).
             */
            fused: number;
            /**
             * Format: float
             * @description `ts_rank_cd`, normalised to 0..1.
             */
            keyword?: number | null;
            /**
             * Format: int32
             * @description 1-based rank in the keyword list.
             */
            keyword_rank?: number | null;
            /**
             * Format: float
             * @description Cross-encoder score (model specific scale), when reranked.
             */
            rerank?: number | null;
            /**
             * Format: float
             * @description Cosine similarity to the query.
             */
            semantic?: number | null;
            /**
             * Format: int32
             * @description 1-based rank in the semantic list.
             */
            semantic_rank?: number | null;
        };
        /** @description How a search ran. */
        SearchMeta: {
            /** @description `true` when the search ran in a weaker mode than requested. */
            degraded: boolean;
            /** @description More results follow this page. */
            has_more: boolean;
            /** @description The mode that actually ran: `keyword` when semantic search was unavailable. */
            mode: components["schemas"]["SearchMode"];
            /** @description The query as searched (trimmed). */
            query: string;
            requested_mode: components["schemas"]["SearchMode"];
            /** @description `true` when the top results were reordered by the reranker. */
            reranked: boolean;
            /**
             * @description "Did you mean": the query with misspelt-looking words replaced by similar
             *     words from your documents. Only when keyword search found few matches.
             */
            suggestion?: string | null;
            timings: components["schemas"]["Timings"];
            /** @description Why the search was degraded or not reranked, for display or debugging. */
            warnings: string[];
        };
        /**
         * @description Which retrievers a search uses.
         * @enum {string}
         */
        SearchMode: "keyword" | "semantic" | "hybrid";
        /** @description A file similar to another one. */
        SimilarFile: {
            file: components["schemas"]["FileInfo"];
            /**
             * Format: float
             * @description Cosine similarity of its closest chunk to the source file's mean embedding.
             */
            similarity: number;
        };
        SimilarFiles: {
            /** @description Most similar first. Empty while the file is not embedded yet. */
            items: components["schemas"]["SimilarFile"][];
        };
        /** @description An excerpt of a chunk (plain text, never HTML) with the query terms marked. */
        Snippet: {
            highlights: components["schemas"]["Highlight"][];
            /** @description Up to two fragments joined by " … "; the chunk's start when no term matched. */
            text: string;
        };
        /** @description Milliseconds spent per stage (stages that did not run are 0). */
        Timings: {
            /**
             * Format: double
             * @description Embedding the query.
             */
            embed_ms: number;
            /**
             * Format: double
             * @description Loading result rows and snippets.
             */
            fetch_ms: number;
            /**
             * Format: double
             * @description Keyword and file-name queries (and the spelling suggestion, when made).
             */
            keyword_ms: number;
            /** Format: double */
            rerank_ms: number;
            /**
             * Format: double
             * @description Vector query.
             */
            semantic_ms: number;
            /** Format: double */
            total_ms: number;
        };
        UpdateFileRequest: {
            is_pinned?: boolean | null;
            /** @description New display name (sanitised like uploads). */
            name?: string | null;
            /** @description Replaces all tags. Trimmed and lowercased; at most 32, each 1–50 characters. */
            tags?: string[] | null;
        };
        UpdateMeRequest: {
            /** @description New display name; `null` or blank clears it. */
            display_name?: string | null;
        };
        /** @description `multipart/form-data` body of an upload. */
        UploadForm: {
            /**
             * Format: binary
             * @description The file. Its type is detected from the bytes; the filename is sanitised.
             */
            file: string;
        };
        UserResponse: {
            /** Format: date-time */
            created_at: string;
            display_name?: string | null;
            email: string;
            /** Format: uuid */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; session cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Signed in; session cookie set */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                status?: components["schemas"]["FileStatus"];
                pinned?: boolean;
                /** @description Only files carrying this tag. */
                tag?: string;
                category?: components["schemas"]["FileCategory"];
                /** @description `next_cursor` from the previous page. */
                cursor?: string;
                /** @description Page size, 1–200 (default 50). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileList"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadForm"];
            };
        };
        responses: {
            /** @description Already uploaded: the existing file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResponse"];
                };
            };
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `payload_too_large` or `quota_exceeded` */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description `unsupported_media_type` */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    bulk_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file's bytes, with its detected `Content-Type` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: {
                /** @description First character to return (0-based, in Unicode characters). Default 0. */
                offset?: number;
                /** @description Characters to return, 1-1000000. Default 100000. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description File id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No such file, or not extracted yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reindex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Extraction queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    similar: {
        parameters: {
            query?: {
                /** @description How many files, 1-20 (default 5). */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description File id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarFiles"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    thumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The thumbnail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Not modified (matching `If-None-Match`) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Account deleted; session cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /**
                 * @description What to look for, 1-500 characters. Web-search syntax: `"exact phrase"`,
                 *     `or`, and `-word` to exclude.
                 */
                q: string;
                /** @description `hybrid` (default), `keyword` or `semantic`. */
                mode?: components["schemas"]["SearchMode"];
                /** @description Only files of this kind. */
                type?: components["schemas"]["FileCategory"];
                /** @description Uploaded on or after: a date (`2026-01-31`, UTC) or an RFC 3339 timestamp. */
                from?: string;
                /** @description Uploaded on or before this date (inclusive), or before this RFC 3339 timestamp. */
                to?: string;
                /** @description Comma-separated tags; files must carry all of them. */
                tags?: string;
                /** @description Only pinned (`true`) or unpinned (`false`) files. */
                pinned?: boolean;
                /** @description Comma-separated file ids (up to 100) to search within. */
                file_ids?: string;
                /** @description Results per page, 1-50 (default 10). */
                limit?: number;
                /** @description 1-based page (default 1). Only the first 200 results can be paged through. */
                page?: number;
                /** @description Reorder the top results with the cross-encoder, if one is configured (default true). */
                rerank?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResults"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    search_chunks: {
        parameters: {
            query: {
                /**
                 * @description What to look for, 1-500 characters. Web-search syntax: `"exact phrase"`,
                 *     `or`, and `-word` to exclude.
                 */
                q: string;
                /** @description `hybrid` (default), `keyword` or `semantic`. */
                mode?: components["schemas"]["SearchMode"];
                /** @description Only files of this kind. */
                type?: components["schemas"]["FileCategory"];
                /** @description Uploaded on or after: a date (`2026-01-31`, UTC) or an RFC 3339 timestamp. */
                from?: string;
                /** @description Uploaded on or before this date (inclusive), or before this RFC 3339 timestamp. */
                to?: string;
                /** @description Comma-separated tags; files must carry all of them. */
                tags?: string;
                /** @description Only pinned (`true`) or unpinned (`false`) files. */
                pinned?: boolean;
                /** @description Comma-separated file ids (up to 100) to search within. */
                file_ids?: string;
                /** @description Results per page, 1-50 (default 10). */
                limit?: number;
                /** @description 1-based page (default 1). Only the first 200 results can be paged through. */
                page?: number;
                /** @description Reorder the top results with the cross-encoder, if one is configured (default true). */
                rerank?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkResults"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
