//! `GET /files/{id}/thumbnail`: generated by a job, cached, owner-checked.

use std::io::Cursor;

use axum::{
    body::Body,
    http::{Request, StatusCode, header},
};
use image::{ImageFormat, Rgb, RgbImage};
use sqlx::PgPool;

mod support;
use support::TestApp;

fn png(width: u32, height: u32) -> Vec<u8> {
    let mut out = Cursor::new(Vec::new());
    RgbImage::from_pixel(width, height, Rgb([20, 120, 220]))
        .write_to(&mut out, ImageFormat::Png)
        .expect("png");
    out.into_inner()
}

#[sqlx::test(migrator = "akasha_db::MIGRATOR")]
async fn images_get_a_cached_owner_only_thumbnail(pool: PgPool) {
    let app = TestApp::new(pool);
    let ada = app.user("ada@example.com").await;
    let bob = app.user("bob@example.com").await;
    let file = app.upload(&ada, "photo.png", &png(600, 300)).await.json();
    let path = format!(
        "/api/v1/files/{}/thumbnail",
        file["id"].as_str().expect("id")
    );

    // Not generated yet.
    let early = app.send("GET", &path, &ada, None).await;
    assert_eq!(early.status, StatusCode::NOT_FOUND);
    app.run_jobs().await;

    let res = app.send("GET", &path, &ada, None).await;
    assert_eq!(res.status, StatusCode::OK);
    assert_eq!(res.headers[header::CONTENT_TYPE], "image/jpeg");
    assert_eq!(
        res.headers[header::CACHE_CONTROL],
        "private, max-age=604800"
    );
    let hash = file["content_hash"].as_str().expect("hash");
    let etag = res.headers[header::ETAG].to_str().expect("etag").to_owned();
    assert_eq!(etag, format!("\"{hash}-256\""));
    let thumb = image::load_from_memory(&res.bytes).expect("decodes");
    assert_eq!((thumb.width(), thumb.height()), (256, 128));

    let req = Request::get(&path)
        .header(header::COOKIE, &ada)
        .header(header::IF_NONE_MATCH, format!("\"other\", {etag}"))
        .body(Body::empty())
        .expect("request");
    let cached = app.request(req).await;
    assert_eq!(cached.status, StatusCode::NOT_MODIFIED);
    assert!(cached.bytes.is_empty());

    // Other users cannot tell the file exists.
    let other = app.send("GET", &path, &bob, None).await;
    assert_eq!(other.status, StatusCode::NOT_FOUND);
    let anon = app
        .request(Request::get(&path).body(Body::empty()).expect("request"))
        .await;
    assert_eq!(anon.status, StatusCode::UNAUTHORIZED);

    // Deleting the file removes the thumbnail with the blob.
    let id = file["id"].as_str().expect("id");
    let deleted = app
        .send("DELETE", &format!("/api/v1/files/{id}"), &ada, None)
        .await;
    assert_eq!(deleted.status, StatusCode::NO_CONTENT);
    app.run_jobs().await;
    let hash: akasha_storage::ContentHash = hash.parse().expect("hash");
    assert!(
        app.storage
            .get_thumbnail(&hash, 256)
            .await
            .expect("get")
            .is_none()
    );
}

#[sqlx::test(migrator = "akasha_db::MIGRATOR")]
async fn other_types_and_broken_images_have_no_thumbnail(pool: PgPool) {
    let app = TestApp::new(pool);
    let ada = app.user("ada@example.com").await;
    let text = app.upload(&ada, "notes.txt", b"hello").await.json();
    // PNG signature, garbage after it: accepted by the sniffer, undecodable.
    let mut broken = png(10, 10);
    broken.truncate(40);
    let bad = app.upload(&ada, "broken.png", &broken).await.json();
    app.run_jobs().await;

    for file in [text, bad] {
        let path = format!(
            "/api/v1/files/{}/thumbnail",
            file["id"].as_str().expect("id")
        );
        let res = app.send("GET", &path, &ada, None).await;
        assert_eq!(res.status, StatusCode::NOT_FOUND, "{}", file["name"]);
        assert_eq!(res.code(), "not_found");
    }
}
